### ISSUE TITLE
Create docker with Amundsen-Atlas

### ISSUE THREAD

**Issue by bolkedebruin** [lyft/amundsenfrontendlibrary#105]
We should update the readme as well to include the possibility of Atlas as well

**Comment by feng-tao** [comment]
+1, @bolkedebruin @verdan could you guys open a pr for that?

**Comment by jornh** [comment]
That would be super awesome! Having an easy on-ramp to kick the tires and quickly compare and contrast different alternatives using `docker-compose up` or similar FTW.

**Comment by bolkedebruin** [comment]
@feng-tao working on it. Can you ensure there are "official" amundsen docker images? they seem now to be private or not pushed?

**Comment by bolkedebruin** [comment]
This was merged.
