### ISSUE TITLE
Disable Google Analytics by default

### ISSUE THREAD

**Issue by bolkedebruin** [lyft/amundsenfrontendlibrary#109]
Google analytics seems to be enabled by default (although with a key that probably doesn't make sense). I don't think it should be enabled by default within corporate boundaries (our firewalls block this)

**Comment by feng-tao** [comment]
cc @danwom @ttannis

**Comment by danwom** [comment]
That's a good point. I'll push a PR to disable this by default when I have some spare cycles.

**Comment by danwom** [comment]
Working on this now.

**Comment by danwom** [comment]
https://github.com/lyft/amundsenfrontendlibrary/pull/198

**Comment by danwom** [comment]
#198 is merged, let us know if this works for you.

**Comment by bolkedebruin** [comment]
Awesome! @danwom. This was bigger than I expected it to be so thanks!

**Comment by jornh** [comment]
With #198 merged it looks like this issue can be closed?

**Comment by feng-tao** [comment]
thanks
