### ISSUE TITLE
Update readme to include screenshoot of the tool

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsenfrontendlibrary#11]
We should add screenshots for different functionalities of the tool.

**Comment by feng-tao** [comment]
@ttannis @danwom

**Comment by ttannis** [comment]
Agreed, however I'd consider this task to be in waiting until we have a richer example data set that mimics real data.

**Comment by feng-tao** [comment]
@ttannis , just create the issue here to remind us :)
