### ISSUE TITLE
Add  docker push step into CI

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsenfrontendlibrary#116]
Now we have docker image in dockerhub. We should create a new step in CI to publish the image.

**Comment by jinhyukchang** [comment]
Merged https://github.com/lyft/amundsenfrontendlibrary/pull/153

Currently Travis fails with timeout when pulling image of `python/library`
Will take a look later.

Not reverting it as it's not affecting build & publish to Pypi.

**Comment by jinhyukchang** [comment]
Retried the build and it was successful. It seems it's an issue with Travis.
https://github.com/travis-ci/travis-ci/issues/9127

Will create another issue to track this issue.
