### ISSUE TITLE
Enable "npm run tsc"

### ISSUE THREAD

**Issue by ttannis** [lyft/amundsenfrontendlibrary#145]
The "npm run tsc" command currently cannot be used to run type checking because of a current un-investigated error. Developers can rely on "npm run build" and "npm run dev-build" to conduct type checking, but that command wastes a bit of time when all that is needed is to run the type checker instead of completely building the source.

We want to investigate the source of the "npm run tsc" errors and update our code/configurations accordingly for it to work.

**Comment by feng-tao** [comment]
thanks @alran . I think the issue could be closed now.
