### ISSUE TITLE
No data/table visible in frontend

### ISSUE THREAD

**Issue by ashitabh** [lyft/amundsenfrontendlibrary#172]
I don't see any table in frontend 
I tried with sample data builder , I can see the 2 tables in Neo4j 
MATCH (n:Table) RETURN n LIMIT 25
and 2 entries in elastic search
hive://gold.test_schema/test_table1
dynamo://gold.test_schema/test_table2

however , UI is still not showing any table

**Comment by ashitabh** [comment]
neo4j somehow was not connecting , any its working now

**Comment by feng-tao** [comment]
thanks @ashitabh . good to hear :)
