### ISSUE TITLE
A small FE data preview UI glitch - if you run *without* SuperSet integration

### ISSUE THREAD

**Issue by jornh** [lyft/amundsenfrontendlibrary#202]
With Quickstart on the recent v1.0.6 compose file i see a small "lie" with it showing the newly introduced loading spinner:

![image](https://user-images.githubusercontent.com/766423/59878728-523d0e80-93a9-11e9-8e06-d8572e46b331.png)

**Comment by feng-tao** [comment]
cc @ttannis @danwom

**Comment by feng-tao** [comment]
@jornh , I am wondering did you get Amundsen integrated with airflow?

**Comment by jornh** [comment]
@feng-tao Nope, but glad you noticed my teaser image 😉 for the Quickstart demo for populating the `DAG` - `write_to` -> `Table` model.

I will do a PR probably early next week.

**Comment by jornh** [comment]
PR https://github.com/lyft/amundsendatabuilder/pull/94 submitted as mentioned above

**Comment by ttannis** [comment]
@jornh thanks for catching this. A one line change caused a regression in our application state management.

**Comment by jornh** [comment]
Can confirm #210 resolves my OP issue:

![image](https://user-images.githubusercontent.com/766423/60372287-79748b00-99fc-11e9-99a5-96ae563b21f6.png)

Thank you @ttannis! 🙂
