### ISSUE TITLE
Add support for OpenID Connect (OIDC)

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenfrontendlibrary#37]

**Comment by feng-tao** [comment]
cc @ttannis @jinhyukchang 
@verdan , my understanding is some of the existing Flask framework has supported OpenID
(https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-openid) which you could inject the flask framework in runtime. At Lyft, we actually inject lyft specific flask framework internally and use SAML authentication which I believe we could do the same for OpenID.

**Comment by verdan** [comment]
> cc @ttannis @jinhyukchang
> @verdan , my understanding is some of the existing Flask framework has supported OpenID
> (https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-openid) which you could inject the flask framework in runtime. At Lyft, we actually inject lyft specific flask framework internally and use SAML authentication which I believe we could do the same for OpenID.

Ah, nice! We'll do something similar, thanks @feng-tao 
So, I'm perfectly okay to close this issue if we've no plans to explicitly support OIDC for Amundsen.

**Comment by jinhyukchang** [comment]
@verdan Cool. Let us know how it goes. Closing.
