### ISSUE TITLE
Update roadmap.md

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsenfrontendlibrary#41]
cc @markgrover @philippemizrahi

**Comment by feng-tao** [comment]
we should include all our upcoming planned features to provide the transparency for the external communities.

**Comment by jornh** [comment]
Looks like what's stated in these few slides I just shamelessly clipped from the new presentation you just linked to in the `README` - might be a good beginning: 😄 

https://www.slideshare.net/JrnAHansen/clipboards/my-clips

**Comment by feng-tao** [comment]
thanks @jornh  :) cc @markgrover @philippemizrahi

**Comment by jornh** [comment]
I guess with https://github.com/lyft/amundsenfrontendlibrary/pull/235 (and it’s 🐑 clone in the umbrella repo) this is resolved?

**Comment by ttannis** [comment]
Yep. https://github.com/lyft/amundsen/pull/20
