### ISSUE TITLE
Only one data source owner

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenfrontendlibrary#62]
Technically there should only be one data owner (the one who created that source/table), but we are allowing multiple owners for the tables. 
At the moment, **Owned By** allows you to put multiple owners on the table detail page.

**Comment by feng-tao** [comment]
@verdan , that's correct at this moment. At Lyft, our table could be owned by team as well as user.

**Comment by verdan** [comment]
Emm, yes I think the difference is Owned by and Created By. I will come back to this thing later with more details. Closing this for now.
