### ISSUE TITLE
Different UI

### ISSUE THREAD

**Issue by tomsej** [lyft/amundsenfrontendlibrary#65]
Hi! I have just installed whole Amundsen stack and it looks different to your attached screenshots:

My screenshot
![image](https://user-images.githubusercontent.com/6624716/55491239-69cfeb00-5635-11e9-8c9e-6b507be3d29f.png)

Your screenshot:
![image](https://user-images.githubusercontent.com/6624716/55491634-21fd9380-5636-11e9-8557-0b249aad527f.png)

I am curious if I did not build frontend correctly (do not see any errors in console) or the UI is still WIP and attached images are mockups or you do not want to share your Lyft styling.

Sorry, I did not find any mention in any README and it can be confusing also for others.

Thanks a lot!

**Comment by feng-tao** [comment]
cc @ttannis @danwom 
@tomsej thanks for trying out Amundsen. But you are correct, the screenshoot is served as a design mock for the tool. Currently we haven't been able to share the Lyft styling and still work on build a generic color scheme for the tool in open source world.

In terms of the color scheme of the tool, I will let @ttannis  or @danwom  to answer as they have better context. And not sure if you are aware, Amundsen actually have 4 repos and you could do a quick start to see the e2e experience per https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/installation.md .

The tool is currently being actively developed. Feel free to join our slack workspace to ask us any questions. Thanks again for trying out our tool.

**Comment by tomsej** [comment]
Thank you @feng-tao I am closing this issue!
