### ISSUE TITLE
Could not join Slack channel

### ISSUE THREAD

**Issue by tomsej** [lyft/amundsenfrontendlibrary#66]
I could not join [Slack channel](https://amundsenworkspace.slack.com/join/shared_invite/enQtNTU5NDAzOTIzNDI3LTM3MzJkMTAxYzY4Y2U2YTI0OGQ4OTE5NWI2YzEzZTJmZDkzMzFmZDAxZjg3YjlkY2IwMGE0ZTkzMDlkMTQ5YTA), seems that link is no longer active.

Sorry for making a new issue :/ but it is usually easier to find.

**Comment by feng-tao** [comment]
@tomsej , sorry about that. It seems the original invitation link expired. I just created a new one(https://join.slack.com/t/amundsenworkspace/shared_invite/enQtNTk2ODQ1NDU1NDI0LWVmZWM4ZWQ4MzdjYjEzNmU5NDcwMmFiMDY5YjBlMWY3MTgyNjdjZDk4MGYxZTEyZjg2NThlODdlMTQwOGZiYTY) which shouldn't expire . Let me know if you still encounter any issues. I will update the readme as well.

**Comment by feng-tao** [comment]
@tomsej , the slack link in readme.md has been updated :)
