### ISSUE TITLE
Document how to integrate amundsenfrontend with Apache superset

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsenfrontendlibrary#69]
At Lyft, we integrate Amundsen with Apache superset for table data preview as well as sql exploration. We should document how we do the integration (e.g which endpoint we call superset to get the preview data etc)

**Comment by feng-tao** [comment]
cc @danwom @ttannis

**Comment by feng-tao** [comment]
FYI @verdan

**Comment by verdan** [comment]
@feng-tao it would be nice to have this doc available anytime soon :)

**Comment by feng-tao** [comment]
@verdan , I only knew we used https://github.com/apache/incubator-superset/blob/959c35d506759bdbea48db55ef61677f4c1ebd7d/superset/views/core.py#L2589 to get the data preview from superset sqllab. But I will defer it to @ttannis  as she and Max(@mistercrunch) did the setup :( I never setup superset locally before.

**Comment by feng-tao** [comment]
And for the context, we have an internal version of superset client in Amundsen which uses internal ACL header to query superset as we need to pass user session info to superset to Authz and see if the user is allowed to see the actual data.

I think we could modify the client to make it open source able. The difficult part is that both of us haven't setup the master branch of superset locally before. So it will be a bit hard to test it out our client whether it works against the OSS version.

**Comment by feng-tao** [comment]
cc @youngyjd as he did setup superset locally before.

**Comment by ttannis** [comment]
Addressed with https://github.com/lyft/amundsenfrontendlibrary/pull/159
