### ISSUE TITLE
Update setup script to add requirements

### ISSUE THREAD

**Issue by verdan** [lyft/amundsenfrontendlibrary#79]
In order to make amundsen work using pip, we need to add the requirements under `install_requires` in setup.py. 

P.S: We don't have that much requirements, so we can avoid dividing the requirements in separate files i.e., test, dev etc, and do something like this: (but yeah that would add extra testing packages for end users)

```
requirements_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'requirements3.txt')
with open(requirements_path) as requirements_file:
    requirements = requirements_file.readlines()

setup(
    ...
    install_requires=requirements,
    ...
)
```

**Comment by verdan** [comment]
cc: @feng-tao

**Comment by feng-tao** [comment]
https://github.com/lyft/amundsenfrontendlibrary/pull/82

**Comment by feng-tao** [comment]
pr is merged. close this issue.
