### ISSUE TITLE
Fix eslint error

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsenfrontendlibrary#84]
ERROR: /Users/tfeng/tmp/amundsenfrontendlibrary/amundsen_application/static/js/components/NavBar/index.tsx[6, 1]: Multiple imports from 'react-router-dom' can be combined into one.
ERROR: /Users/tfeng/tmp/amundsenfrontendlibrary/amundsen_application/static/js/components/ProfilePage/index.tsx[111, 22]: This expression is unnecessarily compared to a boolean. Just negate it.
ERROR: /Users/tfeng/tmp/amundsenfrontendlibrary/amundsen_application/static/js/components/SearchPage/index.tsx[228, 9]: Identifier 'title' is never reassigned; use 'const' instead of 'let'.
ERROR: /Users/tfeng/tmp/amundsenfrontendlibrary/amundsen_application/static/js/ducks/search/reducer.ts[61, 7]: Identifier 'newState' is never reassigned; use 'const' instead of 'let'.

**Comment by ttannis** [comment]
I confirmed my suspicion that lint errors were making it past the Travis tests, it's a quick fix once I found out why that happened. Thanks for flagging this.

**Comment by ttannis** [comment]
Fixed by #94
